<a href="https://colab.research.google.com/github/ismael-almazan/PNL/blob/main/Ejercicios_de_representaci%C3%B3n_de_texto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Maestría en Inteligencia Artificial y Analítica de Datos<h1>
<h2>Procesamiento de Lenguaje Natural<h2>
<h2> Tarea: Ejercicios de representación de texto <h2>
<h3>Estudiante: Ismael Almazan Luna<h3>
Fecha : 06 de marzo de 2026

# Ejercicios de representación de texto

Considera el pequeño corpus de reseñas de películas y comentarios de redes sociales que está al final del documento y realiza los siguientes ejercicios:

In [1]:
corpus_es = [
    "Me encantó la película, los actores fueron increíbles",
    "No me gustó la película, el guion fue muy malo",
    "La actuación fue excelente, pero la historia era predecible",
    "Película aburrida, me dormí a la mitad",
    "¡Maravillosa! Recomiendo esta película a todos mis amigos",
    "El guion estaba mal escrito, pero la actuación salvó la película",
    "Demasiado larga y lenta, no la volvería a ver",
    "Me gustó mucho, los efectos especiales fueron impresionantes",
    "No es mala, pero esperaba algo más emocionante",
    "Una obra maestra del cine español, increíble dirección",
    "El final fue confuso, no entendí nada",
    "Excelente cinematografía, pero el guion flojo",
    "Demasiado predecible, ya sabía lo que iba a pasar",
    "Me reí mucho, muy divertida y entretenida",
    "La música fue espectacular, pero los actores no convencieron",
    "Película mediocre, no aporta nada nuevo",
    "Excelente historia, emocionante hasta el final",
    "No me gustó la ambientación, parecía de bajo presupuesto",
    "Muy buena dirección y fotografía, la recomiendo",
    "El guion tenía agujeros, pero los efectos visuales impresionan",
    "Aburrida, diálogo poco natural",
    "Gran actuación de los protagonistas, realmente me impactó",
    "El ritmo es lento, pero la historia es interesante",
    "No la recomiendo, desperdicié mi tiempo",
    "Un clásico moderno, me encantó cada escena",
    "Las escenas de acción fueron espectaculares",
    "El humor es pobre y los personajes poco creíbles",
    "Me emocioné, la historia me llegó al corazón",
    "La trama es confusa y difícil de seguir",
    "Película fantástica, muy bien lograda"
]

In [24]:
# Librerias requeridas
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

## Ejercicio 1: Utiliza el texto crudo (sin procesar)
*   Crear un CountVectorizer y un TfidfVectorizer.
*	Aplícalos al corpus y transformar los textos.
*	Mostrar:
    *	Dimensiones de la matriz resultante.
    *	Primeros 10 tokens y sus índices.
*	Comparar las diferencias entre ambas matrices (CountVectorizer y TfidfVectorizer), mencionando de manera general las diferencias observadas.

*La principal diferencia entre las matrices generadas por CountVectorizer y TfidfVectorizer es que la primera representa el número de veces que aparece cada palabra en los documentos, por lo que los valores son frecuencias enteras. En cambio, TF-IDF asigna pesos a las palabras considerando su frecuencia en el documento y su importancia en todo el corpus, por lo que los valores son decimales y las palabras muy comunes tienen menor peso.*

In [29]:
#  CounVectorizer
def fcountvectorizer(docs):

    vectorizer = CountVectorizer(lowercase=False)

    X = vectorizer.fit_transform(docs)

    # DataFrame
    bow_df = pd.DataFrame(
        X.toarray(),
        columns=vectorizer.get_feature_names_out()
    )


    return bow_df

bow_df = fcountvectorizer(corpus_es)
#Dimension de la matriz
print("Dimensión de la matriz: ",bow_df.shape)
#Primeros 10 tokens y sus índices
print("\n CounVectorizer (frecuencia)")
display(bow_df.head(10))




#  TfidfVectorizer
def ftfidfvectorizer(docs):
    vectorizer = TfidfVectorizer(lowercase=False)

    X = vectorizer.fit_transform(docs)

    # DataFrame
    tfidf_df = pd.DataFrame(
        X.toarray(),
        columns=vectorizer.get_feature_names_out()
    )

    return tfidf_df

tfidf_df = ftfidfvectorizer(corpus_es)
#Dimension de la matriz
print("\n Dimensión de la matriz: ",tfidf_df.shape)
#Primeros 10 tokens y sus índices
print("\n TfidfVectorizer (frecuencia)")
display(tfidf_df.head(10))

Dimensión de la matriz:  (30, 136)

 CounVectorizer (frecuencia)

,Aburrida,Demasiado,El,Excelente,Gran,La,Las,Maravillosa,Me,Muy,...,salvó,seguir,tenía,tiempo,todos,trama,ver,visuales,volvería,ya
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
5,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
7,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

 Dimensión de la matriz:  (30, 136)

 TfidfVectorizer (frecuencia)

,Aburrida,Demasiado,El,Excelente,Gran,La,Las,Maravillosa,Me,Muy,...,salvó,seguir,tenía,tiempo,todos,trama,ver,visuales,volvería,ya
0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.334091,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
1,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
2,0.0,0.000000,0.000000,0.0,0.0,0.334551,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
3,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
4,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.390134,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.390134,0.0,0.000000,0.0,0.000000,0.0
5,0.0,0.000000,0.253148,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.358404,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
6,0.0,0.375551,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.421205,0.0,0.421205,0.0
7,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.310067,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
8,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
9,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0

##  Ejercicio 2: Preprocesa el texto eliminando los acentos y stopwords, así como convirtiéndolo a minúsculas.
*	Realiza las mismas actividades que en el ejercicio anterior.
*	Compara las matrices del ejercicio anterior con las matrices que obtuviste en este ejercicio, mencionando de manera general las diferencias observadas.

 *Después del preprocesamiento del texto (convertir a minúsculas, eliminar acentos y quitar stopwords), el vocabulario se reduce y las matrices tienen menos columnas, ya que se eliminan palabras que aportan poca informacion. Además, las palabras se estandarizan, lo que permite que la representación del texto sea más limpia y enfocada en los términos más relevantes.*

In [27]:
# Para eliminar lss stopwords se puede hacer desde la lista de stop ya que contiene la libreria de NLTK, ya que CountVectorizer solo funciona para ingles
nltk.download('stopwords')
stopwords_es = stopwords.words('spanish')



#  CounVectorizer
def fcountvectorizer(docs):

    vectorizer = CountVectorizer(lowercase=True, strip_accents='unicode', stop_words=stopwords_es)

    X = vectorizer.fit_transform(docs)

    # DataFrame
    bow_df = pd.DataFrame(
        X.toarray(),
        columns=vectorizer.get_feature_names_out()
    )

    return bow_df

bow_df = fcountvectorizer(corpus_es)
#Dimension de la matriz
print("Dimensión de la matriz: ",bow_df.shape)
#Primeros 10 tokens y sus índices
print("\n CounVectorizer (frecuencia)")
display(bow_df.head(10))




#  TfidfVectorizer
def ftfidfvectorizer(docs):
    vectorizer = TfidfVectorizer(lowercase=True, strip_accents='unicode', stop_words=stopwords_es)

    X = vectorizer.fit_transform(docs)

    # DataFrame
    tfidf_df = pd.DataFrame(
        X.toarray(),
        columns=vectorizer.get_feature_names_out()
    )

    return tfidf_df

tfidf_df = ftfidfvectorizer(corpus_es)
#Dimension de la matriz
print("\n Dimensión de la matriz: ",tfidf_df.shape)
#Primeros 10 tokens y sus índices
print("\n TfidfVectorizer (frecuencia)")
display(tfidf_df.head(10))

Dimensión de la matriz:  (30, 97)
CounVectorizer (frecuencia)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['eramos', 'estabamos', 'estais', 'estan', 'estara', 'estaran', 'estaras', 'estare', 'estareis', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'esteis', 'esten', 'estes', 'estuvieramos', 'estuviesemos', 'fueramos', 'fuesemos', 'habeis', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habra', 'habran', 'habras', 'habre', 'habreis', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hayais', 'hubieramos', 'hubiesemos', 'mas', 'mia', 'mias', 'mio', 'mios', 'seais', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seria', 'seriais', 'seriamos', 'serian', 'serias', 'si', 'tambien', 'tendra', 'tendran', 'tendras', 'tendre', 'tendreis', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias', 'teneis', 'tengais', 'tenia', 'teniais', 'teniamos', 'tenian', 'tenias', 'tuvieramos', 'tuviesemos'] not in stop_words.
  warnings.warn(

,aburrida,accion,actores,actuacion,agujeros,ambientacion,amigos,aporta,bajo,bien,...,ritmo,sabia,salvo,seguir,tenia,tiempo,trama,ver,visuales,volveria
0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Dimensión de la matriz:  (30, 97)
TfidfVectorizer (frecuencia)

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['eramos', 'estabamos', 'estais', 'estan', 'estara', 'estaran', 'estaras', 'estare', 'estareis', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'esteis', 'esten', 'estes', 'estuvieramos', 'estuviesemos', 'fueramos', 'fuesemos', 'habeis', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habra', 'habran', 'habras', 'habre', 'habreis', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hayais', 'hubieramos', 'hubiesemos', 'mas', 'mia', 'mias', 'mio', 'mios', 'seais', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seria', 'seriais', 'seriamos', 'serian', 'serias', 'si', 'tambien', 'tendra', 'tendran', 'tendras', 'tendre', 'tendreis', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias', 'teneis', 'tengais', 'tenia', 'teniais', 'teniamos', 'tenian', 'tenias', 'tuvieramos', 'tuviesemos'] not in stop_words.
  warnings.warn(

,aburrida,accion,actores,actuacion,agujeros,ambientacion,amigos,aporta,bajo,bien,...,ritmo,sabia,salvo,seguir,tenia,tiempo,trama,ver,visuales,volveria
0,0.000000,0.0,0.515968,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
1,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
2,0.000000,0.0,0.000000,0.496498,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
3,0.499118,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
4,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.57167,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
5,0.000000,0.0,0.000000,0.378626,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.464738,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
6,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.456675,0.0,0.456675
7,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
8,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000
9,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000